{% set version = "1.0.0" %}

package:
  name: pycapnp
  version: {{ version }}

source:
  fn: pycapnp-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pycapnp/pycapnp-{{ version }}.tar.gz
  sha256: 9f6fcca349ebf2ec04ca7eacb076aea3e4fcdc010ac33c98b54f0a19d4e5d3e0

build:
  number: 0
  # pycapnp does not support Windows due to the lack of dynamic API support in
  # C++ Cap'n Proto on Windows:
  # https://github.com/jparyani/pycapnp/issues/53
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - setuptools
    - capnproto

  run:
    - python

test:
  imports:
    - capnp

about:
  home: http://jparyani.github.io/pycapnp/
  license: BSD 2-clause
  license_file: LICENSE.md
  summary: A python wrapping of the C++ implementation of the Cap'n Proto library

extra:
  recipe-maintainers:
    - frol
