{% set name = "pycapnp" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # as of 2.0.0, the PyPi source does not include the _custom_build/ directory, which is needed
  # for pip install to work. This is why we are using the GitHub source.
  url: https://github.com/capnproto/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a9e3acc58d8d67a08dbe6c86513b6bbff734a608a7fceb102883a88877643059

build:
  number: 3
  script:
    - copy /y "{{ environ.get('LIBRARY_INC', '') }}\capnp\*.capnp" .\capnp\  # [win]
    - cp -f "{{ environ.get('PREFIX', '') }}/include/capnp"/*.capnp ./capnp/  # [not win]
    # Can't use `pip install` because it doesn't seem there's a way to set this
    # argument that way.
    - python setup.py build_ext --force-system-libcapnp install

requirements:
  build:
    - capnproto                              # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    # <3 because https://github.com/capnproto/pycapnp/issues/319
    - cython <3                              # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - capnproto
    # <3 because https://github.com/capnproto/pycapnp/issues/319
    - cython <3
    - pkgconfig
    - setuptools
    - pip
    - python
  run:
    - python

test:
  source_files:
    - test
    - examples
  requires:
    - python
    - pytest
    - pytest-asyncio
  imports:
    - capnp        # [build_platform == target_platform]
  commands:
    - pytest test  # [build_platform == target_platform]

about:
  home: https://github.com/capnproto/pycapnp
  summary: A cython wrapping of the C++ Cap'n Proto library
  license: BSD-2-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - LehMaxence
