{% set version = "0.5.10" %}

package:
  name: pycapnp
  version: {{ version }}

source:
  fn: pycapnp-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pycapnp/pycapnp-{{ version }}.tar.gz
  sha256: 59f9181091e7030776e434db216373297db41e16eb257fe450102bd29745459f

build:
  number: 1
  # pycapnp does not support Windows due to the lack of dynamic API support in
  # C++ Cap'n Proto on Windows:
  # https://github.com/jparyani/pycapnp/issues/53
  skip: True  # [win]

requirements:
  build:
    - python
    - setuptools
    - capnproto

  run:
    - python

test:
  imports:
    - capnp

about:
  home: http://jparyani.github.io/pycapnp/
  license: BSD 2-clause
  summary: "A python wrapping of the C++ implementation of the Cap'n Proto library"

extra:
  recipe-maintainers:
    - frol
