travis:
  secure:
    BINSTAR_TOKEN: IxY+mbJEZ4QOViT7mnn7VveQKH0nPkjX/l5TsgliwOUsaCnZuK6ic5iL1cgmOFxpEha+b8V7W+jZcVhIIIK9gfIEgmnauWbZ5yDiHb62dHKrgr+6PqQENJ/EJYKl3/CHBWCFhW95I+gn5v1ncvvojEf6cyvu+vipfQx3/dC5TajvgZ8fs9uJsA6RPOWOmHuBs50w/V2NMb0DtW0DZcUQYY3beZ+MhyaR72xANJQv8Ztyut9/Su+TmpVTqjH9ZCyokOHKouu+58exeqlMGvR9JW5UIi8sfWqFQ0A492Vbp92jn0juKPpI41CHW/diDeH0gOUpKVd5pY0LX5adSvvI6KUqjLp6zzwFoEGYqBtNCfuh1qnawJjOIETfuGdImoO+mUSrUJJeiNmvK361oM1gx+/W1W1alcOyBspn3j49VGj7MmDrMt2G8gXXgV/D1KJWB2kuHXiGN9X+3kDyxbHK7VSXQS0fRsP+uQL1gQSLPCWpwUY/lEAULlhd+5+Dg6LiaviOhx4jkhaPjxBoiKyls3EIexqa+WnixLio9SPyec1QP1rd6aBeSkSML+newX0G7qYYS7fPcEUitPI3dXyOzMAlpjLr0ZAOsC+RGQxlfwnAR/ZjTKB32d/98CYGkhFQ4jRqKLZcdNK6OQzBXyRRmJsdylpgG1EJqlEUJxipeWI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
